# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: converter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='converter.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63onverter.proto\"Y\n\nconvertReq\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05isBin\x18\x02 \x01(\x08\x12\x0c\n\x04\x66ile\x18\x03 \x01(\x0c\x12\x11\n\tneedDraco\x18\x04 \x01(\x08\x12\r\n\x05noZip\x18\x05 \x01(\x08\"\x1b\n\x0b\x63onvertResp\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x32\x39\n\tConverter\x12,\n\rconvertToGltf\x12\x0b.convertReq\x1a\x0c.convertResp\"\x00\x62\x06proto3'
)




_CONVERTREQ = _descriptor.Descriptor(
  name='convertReq',
  full_name='convertReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='convertReq.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isBin', full_name='convertReq.isBin', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='convertReq.file', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='needDraco', full_name='convertReq.needDraco', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='noZip', full_name='convertReq.noZip', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=108,
)


_CONVERTRESP = _descriptor.Descriptor(
  name='convertResp',
  full_name='convertResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='convertResp.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['convertReq'] = _CONVERTREQ
DESCRIPTOR.message_types_by_name['convertResp'] = _CONVERTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

convertReq = _reflection.GeneratedProtocolMessageType('convertReq', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTREQ,
  '__module__' : 'converter_pb2'
  # @@protoc_insertion_point(class_scope:convertReq)
  })
_sym_db.RegisterMessage(convertReq)

convertResp = _reflection.GeneratedProtocolMessageType('convertResp', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTRESP,
  '__module__' : 'converter_pb2'
  # @@protoc_insertion_point(class_scope:convertResp)
  })
_sym_db.RegisterMessage(convertResp)



_CONVERTER = _descriptor.ServiceDescriptor(
  name='Converter',
  full_name='Converter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=139,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='convertToGltf',
    full_name='Converter.convertToGltf',
    index=0,
    containing_service=None,
    input_type=_CONVERTREQ,
    output_type=_CONVERTRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONVERTER)

DESCRIPTOR.services_by_name['Converter'] = _CONVERTER

# @@protoc_insertion_point(module_scope)
